### ISSUE TITLE
Mandatory Conditional CF's

### ISSUE THREAD

**Issue by iacob28** [gibus/RT-Extension-ConditionalCustomFields#8]
Hi there,

Is there a way I can make conditional custom fields mandatory ? I don't want the user to be able to create a ticket without filling all the CF's. I've already selected the `Mandatory Validation` for all the custom fields, but it's not working

Thanks

**Comment by gibus** [comment]
Hello,

When you've got CF B which is conditioned by CF A when value of A=x, you can have CF A being mandatory by setting up validation pattern for CF A to "(?#Mandatory).". You can also want CF B to be mandatory (by setting up its validation pattern), in this case CF B will be mandatory if and only if the condition to create/modify CF B is met, that is if A=x. You can take example on the test included in this distribution: https://github.com/gibus/RT-Extension-ConditionalCustomFields/blob/master/xt/mandatory_pattern.t.

**Comment by iacob28** [comment]
Thanks @gibus for your response.

This is my case. Two custom fields CF A and CF B which is conditioned by CF A. 
CF A is Mandatory and it's working fine, but I want the CF B to also be Mandatory . I've selected the Mandatory validation for the CF B, but it's not working. Here is a screen shot from my RT. You can see in the screenshot. I have the **Resources** CF, and the **Name of the Group** CF which is conditioned by **Group Rights** value from **Resources CF** . The `Mandatory Validation ` it's working fine for the **Resources CF** , but it's not working for the **Name of the Group** CF . 

![image](https://user-images.githubusercontent.com/16120714/69540838-5f7dab00-0f90-11ea-884d-32d0934c22aa.png)

**Comment by gibus** [comment]
Strange this is exactly what is tested with https://github.com/gibus/RT-Extension-ConditionalCustomFields/blob/master/xt/mandatory_pattern.t

**Comment by iacob28** [comment]
Can you guide me a little bit ? I'm don't know perl very good . How I can use that perl test file for my RT custom fields ? Sorry and Thank You

**Comment by gibus** [comment]
Hi,
I was just mentioning the test file because it shows there shouldn't be an issue with your case. You cannot use this test file directly. It is supposed to be run in standard RT testing environment. But it has been run, and the test 'Raise error for ConditionedBy mandatory CF when condition is met' has successfuly passed.

Have I understood correctly that it was your case: CF B is conditioned by CF A, CF B is mandatory, the condition is met, CF B has no value for current ticket, but nevertheless no error is risen and you can create/update the ticket?

This is what have been tested. Maybe try to insert some code to log what happens in your case. The code that checks that a conditioned CF which condition is met should fulfill a pattern is after this line:

 https://github.com/gibus/RT-Extension-ConditionalCustomFields/blob/d5ce69c93b92b7df35997ae0904730461a66e1e9/lib/RT/Extension/ConditionalCustomFields.pm#L283

Try to check whether the values of $match variable after the call to $old_MatchPattern function. This will tell you whether the pattern is matched (no error) or not. Then maybe trace what branch of code is taken just after...

I'm sorry, I'm away from a computer for a while, typing this on my phone. But the testing suite gives me confidence that there shouldn't be any issue.

**Comment by gibus** [comment]
Hello, I'm back to office where I have tested that there is indeed an issue! I will provide you a patch during the day…

**Comment by iacob28** [comment]
Thank you @gibus

**Comment by gibus** [comment]
OK, version 1.03 should appear on CPAN in a few minutes.

The issue was that the test I've pointed was only applied in ticket modification, while on ticket creation the check whether the condition is met was done with a wrong HTML object. In creation the HTML object is not built upon the ContextObject of CF (which is an RT::Queue) but upon a null RT::Ticket.
