### ISSUE TITLE
Conditional CF's not working in SelfService with CustomFieldGroupings

### ISSUE THREAD

**Issue by iacob28** [gibus/RT-Extension-ConditionalCustomFields#9]
Hi there,

I have an issue with the plugin, after upgrading to the latest version of the plugin, on one of my RT instance, the conditional cf's are not working anymore for the unprivileged users. On another instance of RT where I didn't upgrade the plugin, the conditional CF's working fine. I have granted the `SeeCustomField` and `ModifyCustomField` rights for Everyone or Unprivileged Users .

Here how cf appears for one of the Unprivileged user

![image](https://user-images.githubusercontent.com/16120714/71091164-4c37b700-21ad-11ea-81f7-f87b324f797c.png)

And this is how appear for one of the Privileged user

![image](https://user-images.githubusercontent.com/16120714/71091250-72f5ed80-21ad-11ea-8403-cead74c90ea6.png)

**Comment by gibus** [comment]
Hello Iacob,

Can you give me some precisions about the case where it doesn't work?

Is it when creating tickets on SelfService (last revison includes a pull request about this case)?

In your screenshots, which CF is condionned by which one for which value? Is the issue that the conditioned CF is displayed (in creation form or in modify form?) while the condtion CF has no value? Are both CFs belonging to the same custom grouping ("Ressources" for what I understand from the screenshots)?

The PR included in last revision is about custom grouping on SelfService, so I suspect it could be the cause of your issue. But I have to reproduce it, that's why I'm asking these precisions. I hope to have time to work on it tomorrow...

**Comment by iacob28** [comment]
The problem is in the `SelfService/Create.html` page.  So in both of my RT Instance I've made some changes in the `Create.html ` file for the `SelfService`. The change that I've made is a local overlay of the self service create page. I've added the custom field groupings code from the `Ticket/Create.html` , because I wanted that the Unprivileged users to see the custom field grouping in the `SelfService/Create.html` page.
But in the other instance of my RT, where I didn't upgrade the plugin to the last version, the conditional custom fields works just fine with the same modified `SelfService/Create.html` template.


All of my custom field in the screen shots that I've upload, are condition by `Resources CF`. In the first screen shoot you can see that none of the CF's are condition by `Resources CF` , I was logged in with an Unprivileged user.

In the second screen shot, I was logged in with a Privileged user and the conditional CF's works just fine. 

I hope you understand my problem.
Thank you

**Comment by gibus** [comment]
Ok thx for the precisions!

It confirms that the PR https://github.com/gibus/RT-Extension-ConditionalCustomFields/pull/7 conflicts with the customization you've made on SelfService/Create.html.

I'm not at office on Wednesday, so for a quick fix, maybe you can update the code on your non-working instance, to reverse this commit: https://github.com/gibus/RT-Extension-ConditionalCustomFields/commit/b20fb7f659692cdf5e88fe13f6b0f05645eaef9e (that is: keep only the "else block").

I don't know whether a "clean" fix is possible, since the issue is caused by having CF custom groupping in SelfService, which is not what regular RT does. The only "clean" solution I can think about now is adding a configuration variable SelfServiceCustomFieldsCustomGroupping, defaulting to false and which you would set to true in your case with your overlay of SelfService/Create.html.

Anyway, tell me if you've managed to fix the issue by updating the code as suggested above.

**Comment by iacob28** [comment]
Thanks for the help @gibus . 

I managed to solve the bug with the reverse to https://github.com/gibus/RT-Extension-ConditionalCustomFields/commit/b20fb7f659692cdf5e88fe13f6b0f05645eaef9e commit. If you have any "cleaner" solution, in features updates of the plugin, let me know.  

For the solution with the configuration variable, is there a variable called `SelfServiceCustomFieldsCustomGroupping` ? I didn't find any variable called like that. 

Thx

**Comment by gibus** [comment]
Great @iacob28! Now that you have tested that the solution fixes the issue, I've implemented the "clean" fix and just upload version 1.04 to cpan, it should appear in a couple of minutes.

There is a variable to setup in your configuration file. This variable is introduced by 1.04 revision, that's why you couldn't find it before. Eventually I've called it `$SelfServiceCustomFieldGroupings` to be consistent with existing `$CustomFieldGroupings `config variable. Here's the update in doc for this release:

---8<------8<------8<------8<------8<------8<------8<------8<------8<------8<------8<------8<------8<---
Usually, groupings of custom fields, as defined in `$CustomFieldGroupings` configuration variable, is _not_ enabled in SelfService. This is the case if you  use RT Core. Anyway, some RT instances could have overridden this restriction to enable groupings of custom fields in SelfService.

In this case, you should add to your configuration file (`/opt/rt4/etc/RT_SiteConfig.pm`) the following line, setting `$SelfServiceCustomFieldGroupings` configuration variable to a true value:

    Set($SelfServiceCustomFieldGroupings, 1);
--->8------>8------>8------>8------>8------>8------>8------>8------>8------>8------>8------>8------>8---

So, in your case, when you'll upgrade to 1.04, you have to insert the above line in your configuration file.

**Comment by iacob28** [comment]
Great ! 

I will update later, and test it. Maybe this modification with CF's grouping I've made to my SelfService, is related to the another issues that I've opened? this issue - #8 . 
I didn't managed to solve that mandatory conditional CF's  in my `SelfService/Create.html` page. It's working fine in Modification page, after the ticket is created, but the Mandatory Conditional CF's, are not working in `SelfService/Create`
